# Generated by Django 5.2.4 on 2025-08-06 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psychapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('psychologist', 'Psychologist')], default='psychologist', max_length=20),
        ),
    ]
